publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.1
  action_slider: ^0.7.0
  cupertino_icons: ^1.0.8
  characters: ^1.4.0
  dynamic_fonts: ^2.2.2
  english_words: ^4.0.0
  modal_bottom_sheet: ^3.0.0
  material_color_utilities: ^0.11.0
  collection: ^1.19.1
  firebase_core: ^3.6.0
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  firebase_auth: ^5.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  boolean_selector: ^2.1.2
  clock: ^1.1.2
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  leak_tracker_flutter_testing: ^3.0.1
  matcher: ^0.12.17
  meta: ^1.16.0
  vm_service: ^15.0.0
  test_api: ^0.7.4
  term_glyph: ^1.2.2
  string_scanner: ^1.4.1
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  crypto: ^3.0.3
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  flutter_svg: ^2.0.9
  cloud_firestore: ^5.6.12
  record: ^5.0.5
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/fonts/
